run: clean
	javac project5/bruteForce/BruteForceDriver.java
	javac project5/dynamicProgramming/DynamicProgrammingDriver.java
	javac project5/backTracking/BackTrackingDriver.java
	javac project5/createFile/CreateKP.java
clean: 
	rm -f project5/*/*.class