run: clean
	javac project5/bruteForce/BruteForce.java
	javac project5/dynamicProgramming/DynamicProgramming.java
	javac project5/backTracking/BackTracking.java
	javac project5/createFile/CreateKP.java
clean: 
	rm -f project5/*/*.class