run:
	ant -buildfile computeMaxProfit/src/build.xml clean
	ant -buildfile computeMaxProfit/src/build.xml all
	ant -buildfile computeMaxProfit/src/build.xml run -Darg0=-m -Darg1=market-price.txt -Dagr2=-p -Darg3=price-list.txt